# Generated by Django 6.1 on 2026-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='geocode_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('exact', 'Exact'), ('non_exact', 'Non Exact'), ('fallback', 'Fallback'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
