# Generated by Django 6.1 on 2026-08-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_fuelstation_geocode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='match_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='geocode_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('exact', 'Exact'), ('approximate', 'Approximate'), ('uncertain', 'Uncertain'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
